name: Build and Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches: ["main"]

jobs:

  build:
    name: Building App
    # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    # env:
      # GH_TOKEN: ${{ secrets.github_token }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.9'
          # python-version: '3.10'
        # if: ${{ startsWith(matrix.os, 'win') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build app with pyinstaller
        run: pyinstaller meshery.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: meshery-${{ matrix.os }}
          path: |
            dist/**/*.app
            dist/**/*.exe

      # - name: Upload Windows artifact
      #   if: ${{ startsWith(matrix.os, 'win') }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: meshery_${{ matrix.os }}
      #     path: dist/**

      # - name: Upload MacOS artifact
      #   if: ${{ startsWith(matrix.os, 'macos') }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: meshery_macos
      #     path: dist/**.app
  
  release:
    needs: build
    name: Release App
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    # if: startsWith(github.ref, 'refs/tags/')  # Only for tags
    # if: github.ref_type == 'tag'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*.zip
