name: Build and Release

on:
  push:
    branches: ["main"]

jobs:

  release:
    name: Building Release
    # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    
    # env:
      # GH_TOKEN: ${{ secrets.github_token }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.9'
          # python-version: '3.10'
        # if: ${{ startsWith(matrix.os, 'win') }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build app with pyinstaller
        run: pyinstaller meshery.spec

      - name: Upload Windows artifact
        if: ${{ startsWith(matrix.os, 'win') }}
        uses: actions/upload-artifact@v3
        with:
          name: meshery_windows
          path: dist/**

      - name: Upload MacOS artifact
        if: ${{ startsWith(matrix.os, 'macos') }}
        uses: actions/upload-artifact@v3
        with:
          name: meshery_macos
          path: dist/**